name: wind-energy-tutorials
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - netcdf4=1.5.3
  - numpy=1.15.4
  - pandas=0.23.4
  - xarray=0.11.0
  - cartopy=0.18.0
  - wrf-python=1.3.2